// Generated by CoffeeScript 1.9.3
var calendar, contacts, dataSystem, emails, files, home, main, proxy, startPouchDB, startStack;

home = require('cozy-home');

dataSystem = require('cozy-data-system');

proxy = require('cozy-proxy');

contacts = require('cozy-contacts');

emails = require('cozy-emails');

files = require('cozy-files');

calendar = require('cozy-calendar');

main = function(opts, callback) {
  return startPouchDB(function() {
    return startStack(function() {
      return contacts({}, function() {
        return emails({}, function() {
          return files(function() {
            return calendar(9113, function() {
              if (typeof callback === "function") {
                callback();
              }
              return setInterval(function() {
                return console.log(process.memoryUsage());
              }, 2000);
            });
          });
        });
      });
    });
  });
};

startStack = function(callback) {
  return dataSystem(function() {
    return home(function() {
      return proxy({
        host: '0.0.0.0'
      }, callback);
    });
  });
};

startPouchDB = function(callback) {
  var PouchDB, app, express;
  express = require('express');
  app = express();
  PouchDB = require('pouchdb');
  app.use('/', require('express-pouchdb')(PouchDB));
  return app.listen(5984, callback);
};

module.exports = main;

if (!module.parent) {
  main();
}
